version: '3.8'
services:
  natolo_db:
    image: postgres:15-alpine
    container_name: natolo_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password_ultra_secret_2026
      POSTGRES_DB: natolocollect
    volumes:
      - natolo_data:/var/lib/postgresql/data

  natolo_api:
    build: ./src/api
    container_name: natolo_api
    restart: always
    environment:
      DATABASE_URL: postgres://admin:password_ultra_secret_2026@natolo_db:5432/natolocollect
    depends_on:
      - natolo_db

  proxy:
    image: nginx:alpine
    container_name: natolo_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - natolo_api

volumes:
  natolo_data:
